config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root 'eshop#index'
  get 'eshop/login'
  get 'eshop/blog_single'
  get 'eshop/blog'
  get 'eshop/cart'
  post 'eshop/cart', to: 'eshop#cart', as: 'coupons'
  # patch 'eshop/cart', to: 'eshop#cart', as: 'coupons'
  get 'eshop/checkout'
  get 'eshop/contact_us'
  get 'eshop/error404'
  # get 'eshop/shopping_cart'
  get 'eshop/product_details/:id', to: 'eshop#product_details', as: 'product_details'
  get 'eshop/shop'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "eshop/add_to_cart/:id", to: "eshop#add_to_cart", as: "add_to_cart"
  delete "eshop/remove_from_cart/:id", to: "eshop#remove_from_cart", as: "remove_from_cart"
  delete "eshop/remove_from_cart1/:id", to: "eshop#remove_from_cart1", as: "remove_from_cart1"
  # Defines the root path route ("/")
  # root "articles#index"
  post "eshop/increase_quantity/:id", to: "eshop#increase_quantity", as: "increase_quantity"
  post "eshop/decrease_quantity/:id", to: "eshop#decrease_quantity", as: "decrease_quantity"


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    user ||= User.new # guest user (not logged in)

    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin  # only admin can access Rails Admin
      can :manage, :dashboard    # allow access to dashboard
    end

    if user.supervisor_role?
      can :manage, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner_management.rb
class BannerManagement < ApplicationRecord
    has_many_attached :picture
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories
    has_many :products, :through=>:product_categories, :dependent => :destroy
    has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
    belongs_to :parent_category, :class_name => "Category", :optional => true
    enum :status, [ :active, :inactive]
end

app/models/configuration.rb
class Configuration < ApplicationRecord
    
end

app/models/coupon.rb
class Coupon < ApplicationRecord
    has_many :coupons_useds
    has_many :users, through: :coupons_useds

    # enum :status, [ :active, :inactive]


end

app/models/coupons_used.rb
class CouponsUsed < ApplicationRecord
  belongs_to :user
  belongs_to :coupon
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories
    has_many :categories, :through=>:product_categories,:dependent => :destroy
    has_many :product_images
    has_many :product_attributes_assoc
    has_many :order_details


    has_one_attached :ProductImage
end

app/models/product_attribute.rb
class ProductAttribute < ApplicationRecord
end

app/models/product_attribute_value.rb
class ProductAttributeValue < ApplicationRecord
end

app/models/product_attributes_assoc.rb
class ProductAttributesAssoc < ApplicationRecord
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    belongs_to :category
    belongs_to :product
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers=> [:google_oauth2, :facebook, :github]
    
  has_many :coupons_useds
  has_many :coupons, through: :coupons_useds
  def self.from_omniauth(auth)

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user_email = auth.info.email.present? ? auth.info.email : "user.#{auth.uid}@gmail.com"
      user.email = user_email
      user.password = Devise.friendly_token[0, 20]
      
    end
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
    has_many :user_orders
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
    has_many :order_details
    belongs_to :coupon
    belongs_to :user
    belongs_to :billing_address, :class_name => 'UserAddress', :foreign_key => 'billing_address_id'
    belongs_to :shipping_address, :class_name => 'UserAddress', :foreign_key => 'shipping_address_id'
  end

app/controllers/eshop_controller.rb
class EshopController < ApplicationController
    skip_before_action :authenticate_user!
    # after_filter :increase_quantity

    def index
        @banners = BannerManagement.all
        @products = Product.all.limit(6)
        @category = Category.where(parent_id: nil)
        

    end
    def shopping_cart
        
    end
    def login
        
    end
    def product_details
        @category = Category.find(params[:id])
        @products = @category.products
    end
    def shop
        
    end

    def blog
        
    end
    def blog_single
        
    end
    def cart
        @sum = 0
       @item = @cart.each do |item|
            @sum += item.price
       end
       @shipping_charge = 25
       @max_shipping_charge = 500
       @user = current_user
       @used_coupon = params[:code]
    #    cp = Coupon.find(5)
       cp = Coupon.find_by(code: @used_coupon)
    #    cp = Coupon.where(code: @used_coupon)
    @coupons = Coupon.all
    # coupons = []
    number_of_uses = 0
    @coupons.each do |c|
        # coupons << c.code
        # coupons.each do |ele|
        if @used_coupon == c.code
            # binding.pry
            if @user.coupons.include?(cp)
                puts "*****coupn already used************************"
            else
                        @percent_off = c.percent_off
                        @total = @sum - @percent_off
                       
                        puts "valid coupon applied"
                        use = c.number_of_uses += 1
                        @user.coupons << c
                        
                    end
                    
                else
                    puts "invalid"
                end
        end
        

      
    end
    def checkout
        
    end
    def contact_us
        
    end
    def error404
        
    end

       
    def add_to_cart
        id = params[:id].to_i
        a = session[:cart] << id unless session[:cart].include?(id)
        # binding.pry   @product_price_lists = [] 
       
        redirect_to root_path
    end
    
    def remove_from_cart
        id = params[:id].to_i
        session[:cart].delete(id)
        redirect_to root_path
    end
    def remove_from_cart1
        id = params[:id].to_i
        session[:cart].delete(id)
        redirect_to eshop_cart_path
    end

   
    def decrease_quantity
        @product_item = Product.find(params[:id])
        @product_item.quantity -= 1
        @product_item.save
    end

    private

    def increase_quantity
        @product_item = Product.find(params[:id])
        session[:quantity] = 0
        @quantity = session[:quantity]
        @quantity += 1

    
        
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eshop_helper.rb
module EshopHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/eshop/blog.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render partial: 'eshop/shared/navbar'%>	
	<section>
		<div class="container">
			<div class="row">
			<%= render partial: 'eshop/shared/sidebar' %>
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">Latest From our Blog</h2>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> Mac Doe</li>
									<li><i class="fa fa-clock-o"></i> 1:33 pm</li>
									<li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
								</ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								
								<%= image_tag("blog/blog-one.jpg") %>

							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							<a  class="btn btn-primary" href="">Read More</a>
						</div>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> Mac Doe</li>
									<li><i class="fa fa-clock-o"></i> 1:33 pm</li>
									<li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
								</ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<%= image_tag("blog/blog-two.jpg") %>
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							<a  class="btn btn-primary" href="">Read More</a>
						</div>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> Mac Doe</li>
									<li><i class="fa fa-clock-o"></i> 1:33 pm</li>
									<li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
								</ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<%= image_tag("blog/blog-three.jpg") %>
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							<a  class="btn btn-primary" href="">Read More</a>
						</div>
						<div class="pagination-area">
							<ul class="pagination">
								<li><a href="" class="active">1</a></li>
								<li><a href="">2</a></li>
								<li><a href="">3</a></li>
								<li><a href=""><i class="fa fa-angle-double-right"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<%= render partial: 'eshop/shared/footer'%>

</body>
</html>

app/views/eshop/cart.html.erb
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<% @cart.each do |product| %>
						
						<tr>
							<td class="cart_product">
								<a href=""><%= image_tag product.ProductImage,class: "imgsize" %></a>
							</td>
							<td class="cart_description">
								<h4><a href=""><%= product.name %></a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
								<p><%= product.price %></p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button flexclass">
								<%= button_to '+', increase_quantity_path(product), method: :patch, remote: true, class:"cart_quantity_up"  %>

									<input class="cart_quantity_input" type="text" name="quantity" value="<%= @quantity %>" autocomplete="off" size="2">
								<%= button_to '-', decrease_quantity_path(product), method: :patch, remote: false, class:"cart_quantity_down"  %>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price"><%= product.price %></p>
							</td>
							<td class="cart_delete">
								<%= link_to remove_from_cart1_path(product),data: {:remote => true, turbo_method: :delete}, class:"cart_quantity_delete" do %>
									<i class="fa fa-times"></i>
								<% end %>
							</td>
						</tr>
							<% end %>

					
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">

					<%= form_with model: @coupon, url: coupons_path,  local: true,data: { turbo: false } do |form| %>
						<ul class="user_option">
							<li>
							<div class="mb-3">
								<%= form.label :coupon_code %>
								<%= form.text_field :code, class: "form-control" , placeholder: "enter coupon code" %>
							</div>
								
							</li>
							
							<li>
								<div class="mb-3">
									<%= form.submit "Apply", class: "btn btn-primary" %>
								</div>
							</li>
						</ul>
						<% end %>
						<ul class="user_info">
							<li class="single_field">
								<label>Country:</label>
								<select>
									<option>United States</option>
									<option>Bangladesh</option>
									<option>UK</option>
									<option>India</option>
									<option>Pakistan</option>
									<option>Ucrane</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
								
							</li>
							<li class="single_field">
								<label>Region / State:</label>
								<select>
									<option>Select</option>
									<option>Dhaka</option>
									<option>London</option>
									<option>Dillih</option>
									<option>Lahore</option>
									<option>Alaska</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
							
							</li>
							<li class="single_field zip-field">
								<label>Zip Code:</label>
								<input type="text">
							</li>
						</ul>
						<a class="btn btn-default update" href="">Get Quotes</a>
						<a class="btn btn-default check_out" href="">Continue</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li>Cart Sub Total <span><%= @sum %></span></li>
							<li>Eco Tax <span>$2</span></li>
							<li>Coupon Off <span><%= @percent_off %></span></li>

							<% if @total.present? && @sum > @max_shipping_charge %>
								<li>Shipping Cost <span>Free</span></li>

							<% elsif @sum.present? && @sum > @max_shipping_charge  %>
								<li>Total <span><%= @shipping_charge = 0  %></span></li>

							<% else %>
								<li>Shipping Cost <span><%= @shipping_charge %></span></li>
							<% end %>
							<% if @total.present? && @total > @max_shipping_charge  %>
								<li>Total <span><%= @total  %></span></li>
							
							<% elsif @sum.present? && @sum < @max_shipping_charge  %>
							<li>Shipping Cost <span><%= @total_sum = @sum + @shipping_charge %></span></li>

							<% else	 %>
								<li>Total <span><%= @sum %></span></li>
							<% end %>
						</ul>
							<a class="btn btn-default update" href="">Update</a>
							<a class="btn btn-default check_out" href="">Check Out</a>
					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->

app/views/eshop/error404.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
	<link href="css/main.css" rel="stylesheet">
	<link href="css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<div class="container text-center">
		<div class="logo-404">
			<a href="index.html"><%= image_tag("home/logo.png", alt: "logo") %></a>
            
		</div>
		<div class="content-404">
            <%= image_tag("404/404.png",class: "img-responsive") %>
			<h1><b>OPPS!</b> We Couldn’t Find this Page</h1>
			<p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
			<h2><a href="index.html">Bring me back Home</a></h2>
		</div>
	</div>

  
    <script src="js/jquery.js"></script>
	<script src="js/price-range.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

app/views/eshop/shared/_navbar.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
	<%= stylesheet_link_tag 'bootstrap.min.css' %>
	<%= stylesheet_link_tag 'font-awesome.min.css' %>
	<%= stylesheet_link_tag 'prettyPhoto.css' %>
	<%= stylesheet_link_tag 'price-range.css' %>
	<%= stylesheet_link_tag 'animate.css' %>
	<%= stylesheet_link_tag 'main.css' %>
	<%= stylesheet_link_tag 'responsive.css' %>
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>

							
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
                        <%= link_to root_path do %>
							<%= image_tag("home/logo.png", alt: "logo") %>
                        <% end %>
						</div>
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canada</a></li>
									<li><a href="#">UK</a></li>
								</ul>
							</div>
							
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									DOLLAR
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canadian Dollar</a></li>
									<li><a href="#">Pound</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li><i class="fa fa-lock">
									<% if user_signed_in? %>
									<%= link_to 'Sign Out', destroy_user_session_path, data: {:turbo_method => :delete} %>
									<% else %>
									<%= link_to 'Sign In', new_user_session_path %>
									<% end %>
									</i></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><%= link_to "Home",root_path %></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><%= link_to 'Products', eshop_shop_path %></li>
										<li><%#= link_to "Product-Details",eshop_product_details_path %></li> 
										<li><%= link_to "Checkout",eshop_checkout_path %></li> 
										<li><%= link_to "Cart", eshop_cart_path %></li> 
										<li><%= link_to "Login",eshop_login_path %></li> 
                                    </ul>
                                </li> 
								<li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><%= link_to 'Blog List',eshop_blog_path %></li>
                                        <li><%= link_to 'Blog Single',eshop_blog_single_path %></li>
                                    </ul>
                                </li> 
                                        <li><%= link_to '404',eshop_error404_path %></li>
                                        <li><%= link_to 'Contact',eshop_contact_us_path %></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

app/views/eshop/shared/_sidebar.html.erb
<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<% @category.each do |category| %>
						  <% sub_categories = category.subcategories rescue nil%>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#<%= category.id %>">
								<span class="badge pull-right"><i class="fa fa-plus"></i></span>
								<%= category.name rescue nil %>
							</a>
									</h4>
								</div>
								<div id="<%= category.id%>" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<% sub_categories.each do |sub_cat| %>
								<li><%= link_to sub_cat.name, product_details_path(sub_cat) %></li>
								<% end %>
										</ul>
									</div>
								</div>
							</div>
							<%end%>
					
					
						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#"> <span class="pull-right">(50)</span>Acne</a></li>
									<li><a href="#"> <span class="pull-right">(56)</span>Grüne Erde</a></li>
									<li><a href="#"> <span class="pull-right">(27)</span>Albiro</a></li>
									<li><a href="#"> <span class="pull-right">(32)</span>Ronhill</a></li>
									<li><a href="#"> <span class="pull-right">(5)</span>Oddmolly</a></li>
									<li><a href="#"> <span class="pull-right">(9)</span>Boudestijn</a></li>
									<li><a href="#"> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->
						
						<div class="shipping text-center"><!--shipping-->
							<%= image_tag("home/shipping.jpg") %>
						</div><!--/shipping-->
					
					</div>
				</div>
				